[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jaspr-cli"
version = "0.1.0"
dependencies = [
    "typer",
    "google-generativeai",
    "jinja2",
    "rich"
]

[project.scripts]
jaspr-cli = "cli:app"
